apiVersion: v1
kind: Service
metadata:
  name: backend-boilerplatedotkonkerdotdev
  namespace: backend-boilerplate
spec:
  selector:
    app: backend-boilerplatedotkonkerdotdev
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
