apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-boilerplatedotkonkerdotdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-boilerplatedotkonkerdotdev
  template:
    metadata:
      labels:
        app: backend-boilerplatedotkonkerdotdev
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend-boilerplatedotkonkerdotdev
          image: 047719649582.dkr.ecr.eu-west-1.amazonaws.com/backend-boilerplate.konker.dev:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
          # optional probes
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 3000
#            initialDelaySeconds: 10
#            periodSeconds: 10
#
