name: '@konker.dev/backend-boilerplate.konker.dev / CD / Development [AWS Serverless]'

on:
  workflow_dispatch:
    inputs:
      extra_args:
        description: "TurboRepo Extra Args"
        required: false
        type: string

#  push:
#    branches:
#      - 'development'
#    paths:
#      - 'apps/backend-boilerplate.konker.dev/src/**'
#      - 'apps/backend-boilerplate.konker.dev/deployment/aws-serverless/**'

env:
  CWD: './apps/backend-boilerplate.konker.dev'
  AWS_DEFAULT_REGION: 'eu-west-1'
  IMAGE_TAG: '${{ github.sha }}'
  TURBO_TELEMETRY_DISABLED: 1
  TURBO_FILTER_ARG: '--filter=@konker.dev/backend-boilerplate.konker.dev'
  TURBO_EXTRA_ARGS: '${{ inputs.extra_args }}'

jobs:
  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: CD Development
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.6.0'

      - uses: actions/cache@v4
        with:
          path: |
            .sst
          key: ${{ runner.os }}-sst

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Assume config management role and export config
      - name: Configure AWS credentials (Configuration management role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_CD_AWS_ACCESS_KEY_ID_BOILERPLATE_BACKEND }}'
          aws-secret-access-key: '${{ secrets.AWS_CD_AWS_SECRET_ACCESS_KEY_BOILERPLATE_BACKEND }}'
          role-to-assume: "arn:aws:iam::047719649582:role/infra/config-management-role" # ${{ env.CONFIG_MANAGEMENT_ROLE_ARN }}
          role-external-id: "configuration-management-access"
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-skip-session-tagging: true # apparently we cannot avoid this
      # TODO

      # Assume application deployment role
      - name: Configure AWS credentials (Application deployment role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_CD_AWS_ACCESS_KEY_ID_BOILERPLATE_BACKEND }}'
          aws-secret-access-key: '${{ secrets.AWS_CD_AWS_SECRET_ACCESS_KEY_BOILERPLATE_BACKEND }}'
          role-to-assume: "arn:aws:iam::898403669204:role/infra/application-deployment-role" # ${{ env.APPLICATION_DEVELOPMENT_ROLE_ARN }}
          role-external-id: "application-deployment-access"
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-skip-session-tagging: true # apparently we cannot avoid this

      - name: Deploy (Development)
        run: |
          cd ./apps/backend-boilerplate.konker.dev
          pnpm sst install --config=./deployment/aws-serverless/sst.config.ts --stage=development --print-logs
          pnpm sst deploy --config=./deployment/aws-serverless/sst.config.ts --stage=development --print-logs
          cd ../../

